// GodotPlugin entry point. Loaded by Godot at startup via the
// `org.godotengine.plugin.v2.${godotPluginName}` meta-data tag in
// AndroidManifest.xml — see plugin/build.gradle for where the placeholder is
// substituted (the `manifestPlaceholders` map in `defaultConfig`).
//
// Responsibility: stand up wry's Android runtime exactly once per process by
// calling `wry::android_setup` (via the Rust JNI shim `initWry` below) on the
// UI thread before any WebView gets built. After that, the gdext-side WebView
// class in libgodot_wry.so handles the per-WebView API like a normal Godot
// node — wry's MainPipe routes the calls back to our WryActivity via JNI.

package org.godotwry.plugin

import android.app.Activity
import android.view.View
import org.godotengine.godot.Godot
import org.godotengine.godot.plugin.GodotPlugin

class GodotWryPlugin(godot: Godot) : GodotPlugin(godot) {
    private var wryActivity: WryActivity? = null

    // `BuildConfig.GODOT_PLUGIN_NAME` is the gradle-generated constant
    // (defined via `buildConfigField` in plugin/build.gradle); single source
    // of truth across the manifest meta-data tag and getPluginName().
    override fun getPluginName(): String = BuildConfig.GODOT_PLUGIN_NAME

    // Required by Godot 4.2+ v2 plugin contract: tells the engine where to
    // find this plugin's bundled `.gdextension` config files so it can load
    // the GDExtension as part of plugin init. Without this override, Godot's
    // gdextension manager never wires up the WebView class even if the
    // .gdextension file is shipped via res://. Path is res://-rooted (NOT
    // relative to the AAR's assets/), per the official template at
    // m4gr3d/GDExtension-Android-Plugin-Template.
    override fun getPluginGDExtensionLibrariesPaths(): Set<String> =
        setOf("res://addons/godot_wry/WRY.gdextension")

    override fun onMainCreate(activity: Activity?): View? {
        // Godot's GodotPlugin abstract signature has Activity as nullable —
        // when this is called the Activity is always non-null in practice
        // (Godot has no plugin-init path without an Activity), but the type
        // system makes us check.
        if (activity == null) {
            Logger.error("onMainCreate received null Activity; skipping wry init")
            return null
        }
        // Build the WryActivity that bridges wry's JNI calls into Godot's
        // Activity. We hold on to the reference for lifecycle forwarding —
        // wry stores a global ref internally, but our lifecycle hooks below
        // need to reach into webview.onPause()/onResume()/destroy().
        val wa = WryActivity(activity)
        wryActivity = wa
        try {
            initWry(wa)
        } catch (t: Throwable) {
            Logger.error("Failed to initialize wry runtime", t)
            wryActivity = null
            throw t
        }
        Logger.info("GodotWryPlugin initialized for activity=${activity::class.java.name}")
        // No fixed View to add to the main layout — the WebView is created
        // later when GDScript instantiates the gdext WebView node, and gets
        // attached to the activity's root via WryActivity.setContentView().
        return null
    }

    override fun onMainResume() {
        wryActivity?.onResume()
    }

    override fun onMainPause() {
        wryActivity?.onPause()
    }

    override fun onMainDestroy() {
        wryActivity?.onDestroy()
        wryActivity = null
    }

    // Implemented in Rust as
    //   `Java_org_godotwry_plugin_GodotWryPlugin_initWry`
    // in godot_wry/rust/src/lib.rs (cfg target_os = "android"). Calls into
    // wry::android_setup on the calling thread.
    private external fun initWry(activity: WryActivity)

    companion object {
        init {
            // Loads libgodot_wry.so. JNI symbols generated by
            // `wry::android_binding!(org_godotwry, plugin)` and our explicit
            // `Java_*_initWry` get bound here. The other Kotlin classes
            // (RustWebView, Ipc, …) also call System.loadLibrary("godot_wry")
            // in their own companion-object init — JVM dedupes, so this is
            // just defense-in-depth in case GodotWryPlugin is the first
            // class in our package the classloader touches.
            System.loadLibrary("godot_wry")
        }
    }
}
